### ISSUE TITLE
Job 1: Completed

### ISSUE THREAD

**Issue by AbdulSuboor-Syed** [AbdulSuboor-Syed/Beam-Python-Section02#1]
Please confirm you have completed Job 1 Successfully :

- [x] Abdul Suboor Syed
- [x] Vineetha Batchu
- [ ] Dhanusha Goud Dommati
- [x] Amulya Mallepalli
- [x] Keerthi Muli
- [x] Vinay Kumar Paspula

**Comment by AbdulSuboor-Syed** [comment]
Successfully completed!

**Comment by vinaypaspula** [comment]
Completed Job 1

**Comment by vineetha-batchu** [comment]
Successfully completed Job1

**Comment by amulyamallepalli** [comment]
Completed Job-1

**Comment by KeerthiMuli** [comment]
completed job 1
